### PR TITLE
2.0 Version of Paper Pager

### PR DESCRIPTION
**Pull request by ZepAviator**
I converted to 2.0 syntax for future. Maybe stick it on a #2.0-preview branch?
There is also now speed and pauseTime properties to adjust the transition timing.

### CODE REVIEW

**Comment by ZepAviator** [comment]
Hrm, seems that some of the tests fail...

**Comment by ZepAviator** [comment]
I think 8px is a closer to material design margin, but I added a mixin so others could tweak further. 
`margin: var(--paper-pager-margin, 8px);`

**Comment by myfrom** [comment]
I think the tests have failed because they're not ready for 2.0
About changes I'm surely gonna put them on production and huge thanks for them but about moving to class syntax I wouldn't be so sure. I sticked to Hybrid syntax (like many if not all elements in 2.0-preview) because it's compatible both with Polymer 2.0 and 1.x and I would stay with that.

**Comment by myfrom** [comment]
I'm closing this. Features that you mentioned (excluding ES6 syntax) will now be a part of #4 and will probably be implemented in 1.0 release.

**Pull request closed without merging**
